CREATE TYPE "public"."finance_app_account_type" AS ENUM('checking', 'savings', 'cash', 'credit_card', 'investment');--> statement-breakpoint
CREATE TYPE "public"."finance_app_category_kind" AS ENUM('income', 'expense');--> statement-breakpoint
CREATE TYPE "public"."finance_app_import_batch_status" AS ENUM('draft', 'reviewing', 'confirmed', 'cancelled', 'reverted');--> statement-breakpoint
CREATE TYPE "public"."finance_app_import_row_status" AS ENUM('pending_review', 'valid', 'invalid', 'ignored', 'duplicate', 'imported');--> statement-breakpoint
CREATE TYPE "public"."finance_app_movement_type" AS ENUM('income', 'expense', 'transfer', 'credit_card_payment', 'balance_adjustment');--> statement-breakpoint
CREATE TYPE "public"."finance_app_transaction_status" AS ENUM('planned', 'confirmed', 'ignored', 'duplicate', 'pending_review');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "finance_app_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"group_id" integer NOT NULL,
	"name" varchar(120) NOT NULL,
	"kind" "finance_app_category_kind" NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_categories_id_user_unique" UNIQUE("id","user_id")
);
--> statement-breakpoint
CREATE TABLE "finance_app_category_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_category_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" varchar(120) NOT NULL,
	"kind" "finance_app_category_kind" NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_category_groups_id_user_kind_unique" UNIQUE("id","user_id","kind")
);
--> statement-breakpoint
CREATE TABLE "finance_app_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" varchar(120) NOT NULL,
	"type" "finance_app_account_type" NOT NULL,
	"institution" varchar(120),
	"initial_balance_cents" integer DEFAULT 0 NOT NULL,
	"currency" varchar(3) DEFAULT 'BRL' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"credit_card_closing_day" integer,
	"credit_card_due_day" integer,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_accounts_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_accounts_initial_balance_cents_non_negative" CHECK ("finance_app_accounts"."initial_balance_cents" >= 0),
	CONSTRAINT "finance_app_accounts_closing_day_valid" CHECK ("finance_app_accounts"."credit_card_closing_day" IS NULL OR ("finance_app_accounts"."credit_card_closing_day" >= 1 AND "finance_app_accounts"."credit_card_closing_day" <= 31)),
	CONSTRAINT "finance_app_accounts_due_day_valid" CHECK ("finance_app_accounts"."credit_card_due_day" IS NULL OR ("finance_app_accounts"."credit_card_due_day" >= 1 AND "finance_app_accounts"."credit_card_due_day" <= 31))
);
--> statement-breakpoint
CREATE TABLE "finance_app_import_batches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_import_batches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"account_id" integer NOT NULL,
	"status" "finance_app_import_batch_status" DEFAULT 'draft' NOT NULL,
	"original_file_name" varchar(255) NOT NULL,
	"source_label" varchar(120),
	"row_count" integer DEFAULT 0 NOT NULL,
	"raw_file_stored" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"confirmed_at" timestamp with time zone,
	CONSTRAINT "finance_app_import_batches_id_user_unique" UNIQUE("id","user_id")
);
--> statement-breakpoint
CREATE TABLE "finance_app_import_rows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_import_rows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"batch_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"row_number" integer NOT NULL,
	"status" "finance_app_import_row_status" DEFAULT 'pending_review' NOT NULL,
	"occurred_on" date,
	"amount_cents" integer,
	"movement_type" "finance_app_movement_type",
	"original_description" text,
	"normalized_description" text,
	"external_id" varchar(255),
	"bank_category" varchar(120),
	"validation_error" text,
	"parsed_data" jsonb,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "finance_app_import_rows_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_import_rows_amount_cents_positive" CHECK ("finance_app_import_rows"."amount_cents" IS NULL OR "finance_app_import_rows"."amount_cents" > 0)
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "finance_app_transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"account_id" integer NOT NULL,
	"destination_account_id" integer,
	"category_id" integer,
	"import_batch_id" integer,
	"import_row_id" integer,
	"movement_type" "finance_app_movement_type" NOT NULL,
	"status" "finance_app_transaction_status" DEFAULT 'confirmed' NOT NULL,
	"amount_cents" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'BRL' NOT NULL,
	"occurred_on" date NOT NULL,
	"original_description" text,
	"description" text NOT NULL,
	"notes" text,
	"external_id" varchar(255),
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_transactions_amount_cents_positive" CHECK ("finance_app_transactions"."amount_cents" > 0)
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_categories" ADD CONSTRAINT "finance_app_categories_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_categories" ADD CONSTRAINT "finance_app_categories_group_user_kind_fk" FOREIGN KEY ("group_id","user_id","kind") REFERENCES "public"."finance_app_category_groups"("id","user_id","kind") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_category_groups" ADD CONSTRAINT "finance_app_category_groups_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_accounts" ADD CONSTRAINT "finance_app_accounts_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD CONSTRAINT "finance_app_import_batches_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD CONSTRAINT "finance_app_import_batches_account_user_fk" FOREIGN KEY ("account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_batch_user_fk" FOREIGN KEY ("batch_id","user_id") REFERENCES "public"."finance_app_import_batches"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_account_user_fk" FOREIGN KEY ("account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_account_user_fk" FOREIGN KEY ("account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_destination_account_user_fk" FOREIGN KEY ("destination_account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_category_user_fk" FOREIGN KEY ("category_id","user_id") REFERENCES "public"."finance_app_categories"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_import_batch_user_fk" FOREIGN KEY ("import_batch_id","user_id") REFERENCES "public"."finance_app_import_batches"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_import_row_user_fk" FOREIGN KEY ("import_row_id","user_id") REFERENCES "public"."finance_app_import_rows"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_categories_user_idx" ON "finance_app_categories" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_categories_user_group_idx" ON "finance_app_categories" USING btree ("user_id","group_id");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_categories_user_group_name_idx" ON "finance_app_categories" USING btree ("user_id","group_id","name");--> statement-breakpoint
CREATE INDEX "finance_app_category_groups_user_idx" ON "finance_app_category_groups" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_category_groups_user_kind_idx" ON "finance_app_category_groups" USING btree ("user_id","kind");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_category_groups_user_kind_name_idx" ON "finance_app_category_groups" USING btree ("user_id","kind","name");--> statement-breakpoint
CREATE INDEX "finance_app_accounts_user_idx" ON "finance_app_accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_accounts_user_active_idx" ON "finance_app_accounts" USING btree ("user_id","is_active");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_accounts_user_name_idx" ON "finance_app_accounts" USING btree ("user_id","name");--> statement-breakpoint
CREATE INDEX "finance_app_import_batches_user_idx" ON "finance_app_import_batches" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_batches_user_account_idx" ON "finance_app_import_batches" USING btree ("user_id","account_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_batches_user_status_idx" ON "finance_app_import_batches" USING btree ("user_id","status");--> statement-breakpoint
CREATE INDEX "finance_app_import_rows_user_idx" ON "finance_app_import_rows" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_rows_user_batch_idx" ON "finance_app_import_rows" USING btree ("user_id","batch_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_rows_user_status_idx" ON "finance_app_import_rows" USING btree ("user_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_import_rows_batch_row_idx" ON "finance_app_import_rows" USING btree ("batch_id","row_number");--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_idx" ON "finance_app_transactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_account_date_idx" ON "finance_app_transactions" USING btree ("user_id","account_id","occurred_on");--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_category_idx" ON "finance_app_transactions" USING btree ("user_id","category_id");--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_type_date_idx" ON "finance_app_transactions" USING btree ("user_id","movement_type","occurred_on");--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_import_idx" ON "finance_app_transactions" USING btree ("user_id","import_batch_id");