CREATE TABLE "finance_app_import_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_import_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" varchar(120) NOT NULL,
	"source_label" varchar(120),
	"config" jsonb NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_import_templates_id_user_unique" UNIQUE("id","user_id")
);
--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD COLUMN "import_template_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_templates" ADD CONSTRAINT "finance_app_import_templates_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_import_templates_user_idx" ON "finance_app_import_templates" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_templates_user_archived_idx" ON "finance_app_import_templates" USING btree ("user_id","is_archived");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_import_templates_user_name_idx" ON "finance_app_import_templates" USING btree ("user_id","name");--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD CONSTRAINT "finance_app_import_batches_template_user_fk" FOREIGN KEY ("import_template_id","user_id") REFERENCES "public"."finance_app_import_templates"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_import_batches_user_template_idx" ON "finance_app_import_batches" USING btree ("user_id","import_template_id");