CREATE TYPE "public"."finance_app_import_rule_text_match_mode" AS ENUM('contains', 'exact');--> statement-breakpoint
CREATE TABLE "finance_app_import_category_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_import_category_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"category_id" integer NOT NULL,
	"account_id" integer,
	"movement_type" "finance_app_movement_type" NOT NULL,
	"normalized_description" text NOT NULL,
	"text_match_mode" "finance_app_import_rule_text_match_mode" DEFAULT 'contains' NOT NULL,
	"amount_cents" integer,
	"amount_tolerance_cents" integer,
	"priority" integer DEFAULT 0 NOT NULL,
	"match_count" integer DEFAULT 0 NOT NULL,
	"accepted_count" integer DEFAULT 0 NOT NULL,
	"rejected_count" integer DEFAULT 0 NOT NULL,
	"overridden_count" integer DEFAULT 0 NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_import_category_rules_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_import_category_rules_type_valid" CHECK ("finance_app_import_category_rules"."movement_type" IN ('income', 'expense')),
	CONSTRAINT "finance_app_import_category_rules_amount_cents_positive" CHECK ("finance_app_import_category_rules"."amount_cents" IS NULL OR "finance_app_import_category_rules"."amount_cents" > 0),
	CONSTRAINT "finance_app_import_category_rules_amount_tolerance_non_negative" CHECK ("finance_app_import_category_rules"."amount_tolerance_cents" IS NULL OR "finance_app_import_category_rules"."amount_tolerance_cents" >= 0)
);
--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD COLUMN "suggestion_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD COLUMN "suggestion_accepted_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD COLUMN "suggestion_rejected_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD COLUMN "suggestion_overridden_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD COLUMN "suggested_category_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD COLUMN "suggested_rule_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD COLUMN "suggestion_source" varchar(40);--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "category_rule_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD CONSTRAINT "finance_app_import_category_rules_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD CONSTRAINT "finance_app_import_category_rules_category_user_fk" FOREIGN KEY ("category_id","user_id") REFERENCES "public"."finance_app_categories"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD CONSTRAINT "finance_app_import_category_rules_account_user_fk" FOREIGN KEY ("account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_import_category_rules_user_idx" ON "finance_app_import_category_rules" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_category_rules_user_archived_idx" ON "finance_app_import_category_rules" USING btree ("user_id","is_archived");--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_suggested_category_user_fk" FOREIGN KEY ("suggested_category_id","user_id") REFERENCES "public"."finance_app_categories"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_category_rule_user_fk" FOREIGN KEY ("category_rule_id","user_id") REFERENCES "public"."finance_app_import_category_rules"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_category_rule_idx" ON "finance_app_transactions" USING btree ("user_id","category_rule_id");