ALTER TABLE "finance_app_category_groups" ADD CONSTRAINT "finance_app_category_groups_id_user_unique" UNIQUE("id","user_id");--> statement-breakpoint
CREATE TYPE "public"."finance_app_monthly_budget_scope" AS ENUM('month', 'category_group', 'category');--> statement-breakpoint
CREATE TABLE "finance_app_monthly_budgets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_monthly_budgets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"month_key" varchar(7) NOT NULL,
	"scope" "finance_app_monthly_budget_scope" NOT NULL,
	"category_group_id" integer,
	"category_id" integer,
	"amount_cents" integer NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_monthly_budgets_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_monthly_budgets_month_key_valid" CHECK ("finance_app_monthly_budgets"."month_key" ~ '^\d{4}-\d{2}$'),
	CONSTRAINT "finance_app_monthly_budgets_amount_positive" CHECK ("finance_app_monthly_budgets"."amount_cents" > 0),
	CONSTRAINT "finance_app_monthly_budgets_scope_columns_valid" CHECK (("finance_app_monthly_budgets"."scope" = 'month' AND "finance_app_monthly_budgets"."category_group_id" IS NULL AND "finance_app_monthly_budgets"."category_id" IS NULL) OR ("finance_app_monthly_budgets"."scope" = 'category_group' AND "finance_app_monthly_budgets"."category_group_id" IS NOT NULL AND "finance_app_monthly_budgets"."category_id" IS NULL) OR ("finance_app_monthly_budgets"."scope" = 'category' AND "finance_app_monthly_budgets"."category_group_id" IS NULL AND "finance_app_monthly_budgets"."category_id" IS NOT NULL))
);
--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budgets" ADD CONSTRAINT "finance_app_monthly_budgets_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budgets" ADD CONSTRAINT "finance_app_monthly_budgets_group_user_fk" FOREIGN KEY ("category_group_id","user_id") REFERENCES "public"."finance_app_category_groups"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budgets" ADD CONSTRAINT "finance_app_monthly_budgets_category_user_fk" FOREIGN KEY ("category_id","user_id") REFERENCES "public"."finance_app_categories"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_monthly_budgets_user_month_idx" ON "finance_app_monthly_budgets" USING btree ("user_id","month_key");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_monthly_budgets_unique_scope_idx" ON "finance_app_monthly_budgets" USING btree ("user_id","month_key","scope","category_group_id","category_id");