CREATE TYPE "public"."finance_app_recurrence_frequency" AS ENUM('once', 'weekly', 'monthly', 'yearly');--> statement-breakpoint
CREATE TABLE "finance_app_recurrences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_recurrences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text,
	"movement_type" "finance_app_movement_type" NOT NULL,
	"account_id" integer NOT NULL,
	"category_id" integer,
	"amount_cents" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'BRL' NOT NULL,
	"frequency" "finance_app_recurrence_frequency" NOT NULL,
	"interval_count" integer DEFAULT 1 NOT NULL,
	"anchor_day" integer,
	"anchor_weekday" integer,
	"starts_on" date NOT NULL,
	"ends_on" date,
	"is_subscription" boolean DEFAULT false NOT NULL,
	"is_bill" boolean DEFAULT false NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_recurrences_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_recurrences_type_valid" CHECK ("finance_app_recurrences"."movement_type" IN ('income', 'expense')),
	CONSTRAINT "finance_app_recurrences_amount_cents_positive" CHECK ("finance_app_recurrences"."amount_cents" > 0),
	CONSTRAINT "finance_app_recurrences_interval_count_positive" CHECK ("finance_app_recurrences"."interval_count" >= 1),
	CONSTRAINT "finance_app_recurrences_anchor_day_valid" CHECK ("finance_app_recurrences"."anchor_day" IS NULL OR ("finance_app_recurrences"."anchor_day" >= 1 AND "finance_app_recurrences"."anchor_day" <= 31)),
	CONSTRAINT "finance_app_recurrences_anchor_weekday_valid" CHECK ("finance_app_recurrences"."anchor_weekday" IS NULL OR ("finance_app_recurrences"."anchor_weekday" >= 0 AND "finance_app_recurrences"."anchor_weekday" <= 6)),
	CONSTRAINT "finance_app_recurrences_ends_on_valid" CHECK ("finance_app_recurrences"."ends_on" IS NULL OR "finance_app_recurrences"."ends_on" >= "finance_app_recurrences"."starts_on"),
	CONSTRAINT "finance_app_recurrences_category_required_for_non_bill" CHECK ("finance_app_recurrences"."is_bill" = true OR "finance_app_recurrences"."category_id" IS NOT NULL),
	CONSTRAINT "finance_app_recurrences_once_ends_on_valid" CHECK ("finance_app_recurrences"."frequency" <> 'once' OR "finance_app_recurrences"."ends_on" IS NULL OR "finance_app_recurrences"."ends_on" = "finance_app_recurrences"."starts_on")
);
--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "recurrence_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "recurrence_occurrence_on" date;--> statement-breakpoint
ALTER TABLE "finance_app_recurrences" ADD CONSTRAINT "finance_app_recurrences_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_recurrences" ADD CONSTRAINT "finance_app_recurrences_account_user_fk" FOREIGN KEY ("account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_recurrences" ADD CONSTRAINT "finance_app_recurrences_category_user_fk" FOREIGN KEY ("category_id","user_id") REFERENCES "public"."finance_app_categories"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_recurrences_user_idx" ON "finance_app_recurrences" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_recurrences_user_archived_idx" ON "finance_app_recurrences" USING btree ("user_id","is_archived");--> statement-breakpoint
CREATE INDEX "finance_app_recurrences_user_frequency_idx" ON "finance_app_recurrences" USING btree ("user_id","frequency");--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_recurrence_user_fk" FOREIGN KEY ("recurrence_id","user_id") REFERENCES "public"."finance_app_recurrences"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_transactions_recurrence_occurrence_idx" ON "finance_app_transactions" USING btree ("recurrence_id","recurrence_occurrence_on") WHERE "finance_app_transactions"."recurrence_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_recurrence_columns_valid" CHECK (("finance_app_transactions"."recurrence_id" IS NULL) = ("finance_app_transactions"."recurrence_occurrence_on" IS NULL));