CREATE TYPE "public"."finance_app_assistant_suggestion_kind" AS ENUM('category_for_transaction', 'category_rule', 'anomaly', 'savings_opportunity');--> statement-breakpoint
CREATE TYPE "public"."finance_app_assistant_suggestion_status" AS ENUM('pending', 'accepted', 'rejected', 'superseded');--> statement-breakpoint
CREATE TABLE "finance_app_assistant_suggestions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_assistant_suggestions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"kind" "finance_app_assistant_suggestion_kind" NOT NULL,
	"fingerprint" varchar(200) NOT NULL,
	"payload" jsonb NOT NULL,
	"reason" text NOT NULL,
	"status" "finance_app_assistant_suggestion_status" DEFAULT 'pending' NOT NULL,
	"decided_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "finance_app_assistant_suggestions" ADD CONSTRAINT "finance_app_assistant_suggestions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_assistant_suggestions_user_status_kind_idx" ON "finance_app_assistant_suggestions" USING btree ("user_id","status","kind");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_assistant_suggestions_pending_unique_idx" ON "finance_app_assistant_suggestions" USING btree ("user_id","kind","fingerprint") WHERE "finance_app_assistant_suggestions"."status" = 'pending';