CREATE TYPE "public"."finance_app_audit_action" AS ENUM('created', 'updated', 'archived', 'restored', 'deleted', 'sanitized', 'purged');--> statement-breakpoint
CREATE TYPE "public"."finance_app_audit_entity_type" AS ENUM('transaction', 'financial_account', 'import_batch', 'assistant_suggestion', 'user_data');--> statement-breakpoint
CREATE TABLE "finance_app_audit_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_audit_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"entity_type" "finance_app_audit_entity_type" NOT NULL,
	"entity_id" integer,
	"action" "finance_app_audit_action" NOT NULL,
	"summary" varchar(240) NOT NULL,
	"diff" jsonb,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "finance_app_audit_events" ADD CONSTRAINT "finance_app_audit_events_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_audit_events_user_created_idx" ON "finance_app_audit_events" USING btree ("user_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "finance_app_audit_events_user_entity_idx" ON "finance_app_audit_events" USING btree ("user_id","entity_type","entity_id");