CREATE TYPE "public"."finance_app_transaction_saved_filter_sort" AS ENUM('date', 'value', 'category');--> statement-breakpoint
CREATE TABLE "finance_app_transaction_saved_filters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_transaction_saved_filters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" varchar(120) NOT NULL,
	"start_on" date NOT NULL,
	"end_on" date NOT NULL,
	"account_id" integer,
	"category_id" integer,
	"movement_type" "finance_app_movement_type",
	"query" text,
	"sort" "finance_app_transaction_saved_filter_sort" DEFAULT 'date' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_transaction_saved_filters_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_transaction_saved_filters_period_valid" CHECK ("finance_app_transaction_saved_filters"."end_on" >= "finance_app_transaction_saved_filters"."start_on")
);
--> statement-breakpoint
ALTER TABLE "finance_app_transaction_saved_filters" ADD CONSTRAINT "finance_app_transaction_saved_filters_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transaction_saved_filters" ADD CONSTRAINT "finance_app_transaction_saved_filters_account_user_fk" FOREIGN KEY ("account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transaction_saved_filters" ADD CONSTRAINT "finance_app_transaction_saved_filters_category_user_fk" FOREIGN KEY ("category_id","user_id") REFERENCES "public"."finance_app_categories"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_transaction_saved_filters_user_idx" ON "finance_app_transaction_saved_filters" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_transaction_saved_filters_user_name_idx" ON "finance_app_transaction_saved_filters" USING btree ("user_id","name");