CREATE TYPE "public"."finance_app_category_group_cash_flow_role" AS ENUM('operational', 'financial');--> statement-breakpoint
ALTER TYPE "public"."finance_app_import_rule_action" ADD VALUE 'transfer';--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" DROP CONSTRAINT "finance_app_import_category_rules_type_valid";--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" DROP CONSTRAINT "finance_app_import_category_rules_action_fields_valid";--> statement-breakpoint
ALTER TABLE "finance_app_category_groups" ADD COLUMN "cash_flow_role" "finance_app_category_group_cash_flow_role" DEFAULT 'operational' NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD COLUMN "source_account_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD COLUMN "destination_account_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD COLUMN "suggested_source_account_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD COLUMN "suggested_destination_account_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD CONSTRAINT "finance_app_import_category_rules_source_account_user_fk" FOREIGN KEY ("source_account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD CONSTRAINT "finance_app_import_category_rules_destination_account_user_fk" FOREIGN KEY ("destination_account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_suggested_source_account_user_fk" FOREIGN KEY ("suggested_source_account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_suggested_destination_account_user_fk" FOREIGN KEY ("suggested_destination_account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD CONSTRAINT "finance_app_import_category_rules_type_valid" CHECK ("finance_app_import_category_rules"."movement_type" IS NULL OR "finance_app_import_category_rules"."movement_type" IN ('income', 'expense', 'transfer'));--> statement-breakpoint
ALTER TABLE "finance_app_import_category_rules" ADD CONSTRAINT "finance_app_import_category_rules_action_fields_valid" CHECK (("finance_app_import_category_rules"."action" = 'categorize' AND "finance_app_import_category_rules"."category_id" IS NOT NULL AND "finance_app_import_category_rules"."source_account_id" IS NULL AND "finance_app_import_category_rules"."destination_account_id" IS NULL AND "finance_app_import_category_rules"."movement_type" IN ('income', 'expense')) OR ("finance_app_import_category_rules"."action" = 'ignore' AND "finance_app_import_category_rules"."category_id" IS NULL AND "finance_app_import_category_rules"."source_account_id" IS NULL AND "finance_app_import_category_rules"."destination_account_id" IS NULL) OR ("finance_app_import_category_rules"."action" = 'transfer' AND "finance_app_import_category_rules"."category_id" IS NULL AND "finance_app_import_category_rules"."source_account_id" IS NOT NULL AND "finance_app_import_category_rules"."destination_account_id" IS NOT NULL AND "finance_app_import_category_rules"."source_account_id" <> "finance_app_import_category_rules"."destination_account_id" AND "finance_app_import_category_rules"."movement_type" IN ('income', 'expense')));