CREATE TABLE "finance_app_monthly_budget_template_skips" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_monthly_budget_template_skips_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"template_id" integer NOT NULL,
	"month_key" varchar(7) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "finance_app_monthly_budget_template_skips_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_monthly_budget_template_skips_month_key_valid" CHECK ("finance_app_monthly_budget_template_skips"."month_key" ~ '^\d{4}-\d{2}$')
);
--> statement-breakpoint
CREATE TABLE "finance_app_monthly_budget_templates" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_monthly_budget_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"scope" "finance_app_monthly_budget_scope" NOT NULL,
	"category_group_id" integer,
	"category_id" integer,
	"amount_cents" integer NOT NULL,
	"starts_at_month_key" varchar(7) NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_monthly_budget_templates_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_monthly_budget_templates_month_key_valid" CHECK ("finance_app_monthly_budget_templates"."starts_at_month_key" ~ '^\d{4}-\d{2}$'),
	CONSTRAINT "finance_app_monthly_budget_templates_amount_positive" CHECK ("finance_app_monthly_budget_templates"."amount_cents" > 0),
	CONSTRAINT "finance_app_monthly_budget_templates_scope_columns_valid" CHECK (("finance_app_monthly_budget_templates"."scope" = 'month' AND "finance_app_monthly_budget_templates"."category_group_id" IS NULL AND "finance_app_monthly_budget_templates"."category_id" IS NULL) OR ("finance_app_monthly_budget_templates"."scope" = 'category_group' AND "finance_app_monthly_budget_templates"."category_group_id" IS NOT NULL AND "finance_app_monthly_budget_templates"."category_id" IS NULL) OR ("finance_app_monthly_budget_templates"."scope" = 'category' AND "finance_app_monthly_budget_templates"."category_group_id" IS NULL AND "finance_app_monthly_budget_templates"."category_id" IS NOT NULL))
);
--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budgets" ADD COLUMN "template_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budget_template_skips" ADD CONSTRAINT "finance_app_monthly_budget_template_skips_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budget_template_skips" ADD CONSTRAINT "finance_app_monthly_budget_template_skips_template_user_fk" FOREIGN KEY ("template_id","user_id") REFERENCES "public"."finance_app_monthly_budget_templates"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budget_templates" ADD CONSTRAINT "finance_app_monthly_budget_templates_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budget_templates" ADD CONSTRAINT "finance_app_monthly_budget_templates_group_user_fk" FOREIGN KEY ("category_group_id","user_id") REFERENCES "public"."finance_app_category_groups"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budget_templates" ADD CONSTRAINT "finance_app_monthly_budget_templates_category_user_fk" FOREIGN KEY ("category_id","user_id") REFERENCES "public"."finance_app_categories"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_monthly_budget_template_skips_user_idx" ON "finance_app_monthly_budget_template_skips" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_monthly_budget_template_skips_template_idx" ON "finance_app_monthly_budget_template_skips" USING btree ("template_id");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_monthly_budget_template_skips_unique_idx" ON "finance_app_monthly_budget_template_skips" USING btree ("template_id","month_key");--> statement-breakpoint
CREATE INDEX "finance_app_monthly_budget_templates_user_idx" ON "finance_app_monthly_budget_templates" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_monthly_budget_templates_user_archived_idx" ON "finance_app_monthly_budget_templates" USING btree ("user_id","is_archived");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_monthly_budget_templates_unique_scope_idx" ON "finance_app_monthly_budget_templates" USING btree ("user_id","scope","category_group_id","category_id");--> statement-breakpoint
ALTER TABLE "finance_app_monthly_budgets" ADD CONSTRAINT "finance_app_monthly_budgets_template_user_fk" FOREIGN KEY ("template_id","user_id") REFERENCES "public"."finance_app_monthly_budget_templates"("id","user_id") ON DELETE no action ON UPDATE no action;