CREATE TYPE "public"."finance_app_card_entry_kind" AS ENUM('charge', 'credit');--> statement-breakpoint
CREATE TABLE "finance_app_card_installment_groups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_card_installment_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"card_id" integer NOT NULL,
	"description" text NOT NULL,
	"total_amount_cents" integer NOT NULL,
	"total_installments" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "finance_app_card_installment_groups_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_card_installment_groups_amount_positive" CHECK ("finance_app_card_installment_groups"."total_amount_cents" > 0),
	CONSTRAINT "finance_app_card_installment_groups_count_positive" CHECK ("finance_app_card_installment_groups"."total_installments" > 0)
);
--> statement-breakpoint
CREATE TABLE "finance_app_card_invoices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_card_invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"card_id" integer NOT NULL,
	"month_key" varchar(7) NOT NULL,
	"closing_date" date NOT NULL,
	"due_date" date NOT NULL,
	"needs_review" boolean DEFAULT false NOT NULL,
	"review_reason" text,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_card_invoices_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_card_invoices_month_key_valid" CHECK ("finance_app_card_invoices"."month_key" ~ '^\d{4}-\d{2}$'),
	CONSTRAINT "finance_app_card_invoices_dates_order" CHECK ("finance_app_card_invoices"."closing_date" <= "finance_app_card_invoices"."due_date")
);
--> statement-breakpoint
CREATE TABLE "finance_app_cards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"name" varchar(120) NOT NULL,
	"institution" varchar(120),
	"closing_day" integer NOT NULL,
	"due_day" integer NOT NULL,
	"limit_cents" integer,
	"default_payment_account_id" integer,
	"legacy_account_id" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "finance_app_cards_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_cards_closing_day_valid" CHECK ("finance_app_cards"."closing_day" >= 1 AND "finance_app_cards"."closing_day" <= 31),
	CONSTRAINT "finance_app_cards_due_day_valid" CHECK ("finance_app_cards"."due_day" >= 1 AND "finance_app_cards"."due_day" <= 31),
	CONSTRAINT "finance_app_cards_limit_cents_positive" CHECK ("finance_app_cards"."limit_cents" IS NULL OR "finance_app_cards"."limit_cents" > 0)
);
--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ALTER COLUMN "account_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ALTER COLUMN "account_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ALTER COLUMN "account_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD COLUMN "card_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD COLUMN "card_invoice_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD COLUMN "card_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD COLUMN "card_invoice_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "card_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "card_invoice_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "card_entry_kind" "finance_app_card_entry_kind";--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "card_installment_group_id" integer;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "installment_number" integer;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD COLUMN "installment_count" integer;--> statement-breakpoint
INSERT INTO "finance_app_cards" (
	"user_id",
	"name",
	"institution",
	"closing_day",
	"due_day",
	"legacy_account_id",
	"is_active",
	"is_archived",
	"created_at",
	"updated_at"
)
SELECT
	"user_id",
	"name",
	"institution",
	COALESCE("credit_card_closing_day", 31),
	COALESCE("credit_card_due_day", 10),
	"id",
	"is_active",
	"is_archived",
	COALESCE("created_at", now()),
	"updated_at"
FROM "finance_app_accounts"
WHERE "type" = 'credit_card'
ON CONFLICT DO NOTHING;--> statement-breakpoint
WITH card_expenses AS (
	SELECT
		t."id" AS transaction_id,
		c."id" AS card_id,
		c."user_id",
		c."closing_day",
		c."due_day",
		t."occurred_on",
		CASE
			WHEN EXTRACT(day FROM t."occurred_on")::int <= c."closing_day"
				THEN date_trunc('month', t."occurred_on")::date
			ELSE (date_trunc('month', t."occurred_on") + interval '1 month')::date
		END AS closing_month
	FROM "finance_app_transactions" t
	JOIN "finance_app_cards" c ON c."legacy_account_id" = t."account_id" AND c."user_id" = t."user_id"
	WHERE t."movement_type" = 'expense' AND t."is_archived" = false
), invoice_dates AS (
	SELECT DISTINCT
		"user_id",
		"card_id",
		(
			"closing_month" +
			(LEAST(
				"closing_day",
				EXTRACT(day FROM (date_trunc('month', "closing_month") + interval '1 month - 1 day'))::int
			) - 1) * interval '1 day'
		)::date AS closing_date,
		(
			(date_trunc('month', "closing_month") +
				CASE WHEN "due_day" > "closing_day" THEN interval '0 month' ELSE interval '1 month' END) +
			(LEAST(
				"due_day",
				EXTRACT(day FROM (date_trunc('month', "closing_month") + CASE WHEN "due_day" > "closing_day" THEN interval '1 month - 1 day' ELSE interval '2 month - 1 day' END))::int
			) - 1) * interval '1 day'
		)::date AS due_date
	FROM card_expenses
), inserted_invoices AS (
	INSERT INTO "finance_app_card_invoices" (
		"user_id", "card_id", "month_key", "closing_date", "due_date", "needs_review", "review_reason", "created_at"
	)
	SELECT
		"user_id",
		"card_id",
		to_char("due_date", 'YYYY-MM'),
		"closing_date",
		"due_date",
		false,
		null,
		now()
	FROM invoice_dates
	ON CONFLICT DO NOTHING
	RETURNING "id"
)
SELECT count(*) FROM inserted_invoices;--> statement-breakpoint
WITH card_expenses AS (
	SELECT
		t."id" AS transaction_id,
		c."id" AS card_id,
		c."user_id",
		c."closing_day",
		c."due_day",
		t."occurred_on",
		CASE
			WHEN EXTRACT(day FROM t."occurred_on")::int <= c."closing_day"
				THEN date_trunc('month', t."occurred_on")::date
			ELSE (date_trunc('month', t."occurred_on") + interval '1 month')::date
		END AS closing_month
	FROM "finance_app_transactions" t
	JOIN "finance_app_cards" c ON c."legacy_account_id" = t."account_id" AND c."user_id" = t."user_id"
	WHERE t."movement_type" = 'expense' AND t."is_archived" = false
), expense_invoice AS (
	SELECT
		ce."transaction_id",
		ce."card_id",
		ci."id" AS invoice_id
	FROM card_expenses ce
	JOIN "finance_app_card_invoices" ci
		ON ci."user_id" = ce."user_id"
		AND ci."card_id" = ce."card_id"
		AND ci."month_key" = to_char((
			(date_trunc('month', ce."closing_month") +
				CASE WHEN ce."due_day" > ce."closing_day" THEN interval '0 month' ELSE interval '1 month' END) +
			(LEAST(
				ce."due_day",
				EXTRACT(day FROM (date_trunc('month', ce."closing_month") + CASE WHEN ce."due_day" > ce."closing_day" THEN interval '1 month - 1 day' ELSE interval '2 month - 1 day' END))::int
			) - 1) * interval '1 day'
		)::date, 'YYYY-MM')
)
UPDATE "finance_app_transactions" t
SET
	"card_id" = ei."card_id",
	"card_invoice_id" = ei."invoice_id",
	"card_entry_kind" = 'charge',
	"account_id" = null
FROM expense_invoice ei
WHERE t."id" = ei."transaction_id";--> statement-breakpoint
WITH migrated_payments AS (
	SELECT
		t."id" AS transaction_id,
		c."id" AS card_id,
		ci."id" AS invoice_id
	FROM "finance_app_transactions" t
	JOIN "finance_app_cards" c ON c."legacy_account_id" = t."destination_account_id" AND c."user_id" = t."user_id"
	JOIN LATERAL (
		SELECT ci.*
		FROM "finance_app_card_invoices" ci
		WHERE ci."user_id" = t."user_id"
			AND ci."card_id" = c."id"
			AND t."occurred_on" > ci."closing_date"
			AND t."occurred_on" <= ci."due_date"
		ORDER BY ci."due_date"
		LIMIT 1
	) ci ON true
	WHERE t."movement_type" = 'credit_card_payment' AND t."is_archived" = false
)
UPDATE "finance_app_transactions" t
SET
	"card_id" = mp."card_id",
	"card_invoice_id" = mp."invoice_id",
	"destination_account_id" = null
FROM migrated_payments mp
WHERE t."id" = mp."transaction_id";--> statement-breakpoint
UPDATE "finance_app_accounts"
SET "is_archived" = true, "is_active" = false
WHERE "type" = 'credit_card';--> statement-breakpoint
ALTER TABLE "finance_app_card_installment_groups" ADD CONSTRAINT "finance_app_card_installment_groups_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_card_installment_groups" ADD CONSTRAINT "finance_app_card_installment_groups_card_user_fk" FOREIGN KEY ("card_id","user_id") REFERENCES "public"."finance_app_cards"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_card_invoices" ADD CONSTRAINT "finance_app_card_invoices_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_card_invoices" ADD CONSTRAINT "finance_app_card_invoices_card_user_fk" FOREIGN KEY ("card_id","user_id") REFERENCES "public"."finance_app_cards"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_cards" ADD CONSTRAINT "finance_app_cards_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_cards" ADD CONSTRAINT "finance_app_cards_default_payment_account_user_fk" FOREIGN KEY ("default_payment_account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_cards" ADD CONSTRAINT "finance_app_cards_legacy_account_user_fk" FOREIGN KEY ("legacy_account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_card_installment_groups_user_idx" ON "finance_app_card_installment_groups" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_card_installment_groups_user_card_idx" ON "finance_app_card_installment_groups" USING btree ("user_id","card_id");--> statement-breakpoint
CREATE INDEX "finance_app_card_invoices_user_idx" ON "finance_app_card_invoices" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_card_invoices_user_card_idx" ON "finance_app_card_invoices" USING btree ("user_id","card_id");--> statement-breakpoint
CREATE INDEX "finance_app_card_invoices_user_due_idx" ON "finance_app_card_invoices" USING btree ("user_id","due_date");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_card_invoices_user_card_month_idx" ON "finance_app_card_invoices" USING btree ("user_id","card_id","month_key");--> statement-breakpoint
CREATE INDEX "finance_app_cards_user_idx" ON "finance_app_cards" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_cards_user_active_idx" ON "finance_app_cards" USING btree ("user_id","is_active");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_cards_user_name_idx" ON "finance_app_cards" USING btree ("user_id","name");--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD CONSTRAINT "finance_app_import_batches_card_user_fk" FOREIGN KEY ("card_id","user_id") REFERENCES "public"."finance_app_cards"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD CONSTRAINT "finance_app_import_batches_invoice_user_fk" FOREIGN KEY ("card_invoice_id","user_id") REFERENCES "public"."finance_app_card_invoices"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_card_user_fk" FOREIGN KEY ("card_id","user_id") REFERENCES "public"."finance_app_cards"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_invoice_user_fk" FOREIGN KEY ("card_invoice_id","user_id") REFERENCES "public"."finance_app_card_invoices"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_card_user_fk" FOREIGN KEY ("card_id","user_id") REFERENCES "public"."finance_app_cards"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_invoice_user_fk" FOREIGN KEY ("card_invoice_id","user_id") REFERENCES "public"."finance_app_card_invoices"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_installment_group_user_fk" FOREIGN KEY ("card_installment_group_id","user_id") REFERENCES "public"."finance_app_card_installment_groups"("id","user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_import_batches_user_card_idx" ON "finance_app_import_batches" USING btree ("user_id","card_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_batches_user_invoice_idx" ON "finance_app_import_batches" USING btree ("user_id","card_invoice_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_rows_user_card_idx" ON "finance_app_import_rows" USING btree ("user_id","card_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_rows_user_invoice_idx" ON "finance_app_import_rows" USING btree ("user_id","card_invoice_id");--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_card_date_idx" ON "finance_app_transactions" USING btree ("user_id","card_id","occurred_on");--> statement-breakpoint
CREATE INDEX "finance_app_transactions_user_invoice_idx" ON "finance_app_transactions" USING btree ("user_id","card_invoice_id");--> statement-breakpoint
ALTER TABLE "finance_app_import_batches" ADD CONSTRAINT "finance_app_import_batches_account_or_card_valid" CHECK (("finance_app_import_batches"."account_id" IS NOT NULL AND "finance_app_import_batches"."card_id" IS NULL AND "finance_app_import_batches"."card_invoice_id" IS NULL) OR ("finance_app_import_batches"."account_id" IS NULL AND "finance_app_import_batches"."card_id" IS NOT NULL AND "finance_app_import_batches"."card_invoice_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "finance_app_import_rows" ADD CONSTRAINT "finance_app_import_rows_account_or_card_valid" CHECK (("finance_app_import_rows"."account_id" IS NOT NULL AND "finance_app_import_rows"."card_id" IS NULL AND "finance_app_import_rows"."card_invoice_id" IS NULL) OR ("finance_app_import_rows"."account_id" IS NULL AND "finance_app_import_rows"."card_id" IS NOT NULL AND "finance_app_import_rows"."card_invoice_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_installment_columns_valid" CHECK (("finance_app_transactions"."card_installment_group_id" IS NULL AND "finance_app_transactions"."installment_number" IS NULL AND "finance_app_transactions"."installment_count" IS NULL) OR ("finance_app_transactions"."card_installment_group_id" IS NOT NULL AND "finance_app_transactions"."installment_number" IS NOT NULL AND "finance_app_transactions"."installment_count" IS NOT NULL AND "finance_app_transactions"."installment_number" > 0 AND "finance_app_transactions"."installment_count" > 0 AND "finance_app_transactions"."installment_number" <= "finance_app_transactions"."installment_count"));--> statement-breakpoint
ALTER TABLE "finance_app_transactions" ADD CONSTRAINT "finance_app_transactions_account_card_shape_valid" CHECK (("finance_app_transactions"."movement_type" = 'expense' AND "finance_app_transactions"."card_id" IS NOT NULL AND "finance_app_transactions"."card_invoice_id" IS NOT NULL AND "finance_app_transactions"."card_entry_kind" IS NOT NULL AND "finance_app_transactions"."account_id" IS NULL AND "finance_app_transactions"."destination_account_id" IS NULL) OR ("finance_app_transactions"."movement_type" = 'credit_card_payment' AND "finance_app_transactions"."account_id" IS NOT NULL AND "finance_app_transactions"."card_id" IS NOT NULL AND "finance_app_transactions"."card_invoice_id" IS NOT NULL AND "finance_app_transactions"."card_entry_kind" IS NULL AND "finance_app_transactions"."destination_account_id" IS NULL AND "finance_app_transactions"."category_id" IS NULL) OR ("finance_app_transactions"."card_id" IS NULL AND "finance_app_transactions"."card_invoice_id" IS NULL AND "finance_app_transactions"."card_entry_kind" IS NULL AND "finance_app_transactions"."account_id" IS NOT NULL));