CREATE TYPE "public"."finance_app_import_routine_kind" AS ENUM('account_statement', 'card_invoice');--> statement-breakpoint
CREATE TABLE "finance_app_import_routine_completions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_import_routine_completions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"routine_item_id" integer NOT NULL,
	"cycle_month_key" varchar(7) NOT NULL,
	"completed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "finance_app_import_routine_completions_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_import_routine_completions_cycle_month_key_valid" CHECK ("finance_app_import_routine_completions"."cycle_month_key" ~ '^\d{4}-\d{2}$')
);
--> statement-breakpoint
CREATE TABLE "finance_app_import_routine_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finance_app_import_routine_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"kind" "finance_app_import_routine_kind" NOT NULL,
	"account_id" integer,
	"card_id" integer,
	"sort_order" integer,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "finance_app_import_routine_items_id_user_unique" UNIQUE("id","user_id"),
	CONSTRAINT "finance_app_import_routine_items_target_valid" CHECK (("finance_app_import_routine_items"."account_id" IS NOT NULL AND "finance_app_import_routine_items"."card_id" IS NULL AND "finance_app_import_routine_items"."kind" = 'account_statement') OR ("finance_app_import_routine_items"."account_id" IS NULL AND "finance_app_import_routine_items"."card_id" IS NOT NULL AND "finance_app_import_routine_items"."kind" = 'card_invoice'))
);
--> statement-breakpoint
ALTER TABLE "finance_app_import_routine_completions" ADD CONSTRAINT "finance_app_import_routine_completions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_routine_completions" ADD CONSTRAINT "finance_app_import_routine_completions_item_user_fk" FOREIGN KEY ("routine_item_id","user_id") REFERENCES "public"."finance_app_import_routine_items"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_routine_items" ADD CONSTRAINT "finance_app_import_routine_items_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_routine_items" ADD CONSTRAINT "finance_app_import_routine_items_account_user_fk" FOREIGN KEY ("account_id","user_id") REFERENCES "public"."finance_app_accounts"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finance_app_import_routine_items" ADD CONSTRAINT "finance_app_import_routine_items_card_user_fk" FOREIGN KEY ("card_id","user_id") REFERENCES "public"."finance_app_cards"("id","user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "finance_app_import_routine_completions_user_idx" ON "finance_app_import_routine_completions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "finance_app_import_routine_completions_user_cycle_idx" ON "finance_app_import_routine_completions" USING btree ("user_id","cycle_month_key");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_import_routine_completions_item_cycle_idx" ON "finance_app_import_routine_completions" USING btree ("user_id","routine_item_id","cycle_month_key");--> statement-breakpoint
CREATE INDEX "finance_app_import_routine_items_user_idx" ON "finance_app_import_routine_items" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_import_routine_items_user_account_idx" ON "finance_app_import_routine_items" USING btree ("user_id","account_id");--> statement-breakpoint
CREATE UNIQUE INDEX "finance_app_import_routine_items_user_card_idx" ON "finance_app_import_routine_items" USING btree ("user_id","card_id");